name: Aggiornamento Old Mod18+

on:
  workflow_dispatch:

concurrency:
  group: tabella-mods18
  cancel-in-progress: false

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests python-telegram-bot==20.0

    - name: Esegui lo script monitor
      run: |
            python ScriptPython/AggiornamentoFileOldMod18.py

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
